In [ ]:
# A recipe for target extraction.

In [17]:
import torch
from jointformer.utils.properties.auto import AutoTarget
import argparse
import multiprocessing as mp
import numpy as np
import os
import math

from jointformer.utils.data import read_strings_from_file

%load_ext autoreload
%autoreload 2

In [18]:
# Configs

REPOSITORY_DIR = '/home/adamizdebski/projects/jointformer'
DATA_DIR = '/home/adamizdebski/files/data'
OUTPUT_DIR = '/home/adamizdebski/files/jointformer/results/chemberta2/moleculenet'

PATH_TO_DATASET_CONFIG   = '/home/adamizdebski/projects/jointformer/configs/datasets/guacamol'
PATH_TO_TOKENIZER_CONFIG = '/home/adamizdebski/projects/jointformer/configs/tokenizers/smiles'
PATH_TO_MODEL_CONFIG = '/home/adamizdebski/projects/jointformer/configs/models/jointformer_test'
PATH_TO_TRAINER_CONFIG = '/home/adamizdebski/projects/jointformer/configs/trainers/test'

In [19]:
os.chdir(REPOSITORY_DIR)

In [20]:
# Data

DATA_FILEPATH = f'{DATA_DIR}/datasets/guacamol/test/smiles.txt'

data = read_strings_from_file(DATA_FILEPATH)
examples = data[:2]


In [21]:
# QED

TARGET_LABEL = 'qed'

oracle = AutoTarget.from_target_label(TARGET_LABEL)
oracle(examples)


Calculating target data: 100%|██████████| 2/2 [00:00<00:00, 409.10it/s]

array([[0.5652006 ],
       [0.13383098]], dtype=float32)

In [22]:
TARGET_FILEPATH = f'{DATA_DIR}/datasets/guacamol/train/{TARGET_LABEL}.npy'
target = np.load(TARGET_FILEPATH)

In [23]:
target.shape

(10000, 1)

In [57]:
# Penalized LogP

TARGET_LABEL = 'plogp'
oracle = AutoTarget.from_target_label(TARGET_LABEL)

oracle(examples)


Calculating target data: 2it [00:00,  6.26it/s]


tensor([[ 0.6528],
        [-0.5677]])

In [58]:
TARGET_FILEPATH = f'{DATA_DIR}/datasets/guacamol/train/{TARGET_LABEL}.npy'
target = np.load(TARGET_FILEPATH)

In [59]:
target.shape

(1273104, 1)

In [64]:
# Guacamol MPO

DATA_FILEPATH = f'{DATA_DIR}/datasets/guacamol/train/10000/seed_0/smiles.txt'
TARGET_LABEL = 'guacamol_mpo'

data = read_strings_from_file(DATA_FILEPATH)
oracle = AutoTarget.from_target_label(TARGET_LABEL)

oracle([data[0], data[1]])


Calculating target data: 2it [00:00, 109.81it/s]


tensor([[1.6952e-01, 3.2928e-01, 4.9755e-02, 3.2129e-01, 3.9429e-22, 4.7077e-01,
         7.9267e-07],
        [1.2596e-01, 6.1987e-01, 6.1701e-01, 2.8868e-01, 1.6791e-07, 3.7842e-02,
         5.3510e-02]])

In [67]:
TARGET_FILEPATH = f'{DATA_DIR}/datasets/guacamol/train/10000/seed_0/{TARGET_LABEL}.npy'
target = np.load(TARGET_FILEPATH)

In [68]:
target.shape

(10000, 7)

In [69]:
# Physicochemical Properties

DATA_FILEPATH = f'{DATA_DIR}/datasets/guacamol/train/smiles.txt'
TARGET_LABEL = 'physchem'

data = read_strings_from_file(DATA_FILEPATH)
oracle = AutoTarget.from_target_label(TARGET_LABEL)

oracle(data[0])


Calculating target data: 1it [00:00, 78.67it/s]


tensor([[9.8705e-01, 1.0608e-03, 1.1928e-03, 1.5063e-03, 4.2665e-03, 1.1835e-03,
         1.4853e-03, 2.2672e-03, 4.3591e-03, 5.3751e-02, 1.8473e-03, 3.6033e-03,
         1.2529e-03, 1.1637e-03, 5.2990e-10, 9.1254e-03, 1.6846e-01, 2.0833e-12,
         2.0941e-01, 1.2566e-14, 6.4078e-01, 6.7277e-07, 6.6211e-05, 8.3925e-01,
         1.5450e-09, 3.6734e-03, 9.7684e-01, 2.4649e-01, 2.0021e-02, 9.8891e-01,
         9.9822e-01, 1.2140e-02, 3.8389e-03, 1.5560e-06, 1.9990e-03, 1.8780e-03,
         6.1356e-01, 1.4697e-03, 1.2098e-02, 3.4839e-02, 1.2098e-02, 9.7911e-03,
         8.9280e-01, 2.8195e-03, 8.2542e-01, 9.6289e-01, 2.8172e-01, 2.0830e-03,
         3.7865e-03, 1.0817e-01, 3.5636e-02, 1.5721e-01, 1.5478e-01, 6.6188e-02,
         3.3555e-02, 1.0796e-01, 1.1551e-02, 2.0409e-02, 1.9592e-08, 2.8389e-02,
         5.3014e-05, 3.1866e-02, 4.2191e-10, 6.2190e-12, 4.6698e-12, 1.9237e-03,
         5.3449e-02, 2.4321e-06, 7.3609e-21, 9.9738e-15, 6.1524e-12, 2.9919e-23,
         1.3366e-01, 8.1803e

In [70]:
TARGET_FILEPATH = f'{DATA_DIR}/datasets/guacamol/train/10000/seed_0/{TARGET_LABEL}.npy'
target = np.load(TARGET_FILEPATH)

In [71]:
target.shape

(10000, 200)